### PR TITLE
Fixed Some Hard Dependency Calls

### PR DESCRIPTION
**Pull request by SirTyler**

### CODE REVIEW

**Comment by MikeLydeamore** [comment]
Any chance of you squashing this into one just so it looks a bit neater? :-)

**Comment by SirTyler** [comment]
I can move all the Bridge calls into just in-line calls instead, was trying to keep what you were doing with what was already there. I did a major clean-up in my own side of the code that I can push into a PR if you want.

**Comment by MikeLydeamore** [comment]
Sorry, I think we've misunderstood here. The Bridge calls were fine as they were, I was just hoping you could 'git squash' into a single commit.
While I appreciate the refactors on all the packages, this isn't something that I'm really wanting to have at the moment. I'm aware the package names don't conform to the regular Java standards, however, this is the formatting that LoveHoly chose, and also matches Ex Nihilo.

If you could revert the refactors, and just keep the hard dependency fixes, then I can merge this in.

**Comment by MikeLydeamore** [comment]
I've implemented this myself, without the refactor, crediting your work. Thank you.

**Pull request closed without merging**
